apiVersion: v1
kind: ResourceQuota
metadata:
 name: count-quotas
spec:
 hard:
   pods: "2"
   
######################################
# apiVersion: v1
# kind: ResourceQuota
# metadata:
#  name: object-counts
# spec:
#  hard:
#    requests.cpu: "1000m"
#    limits.cpu: "2000m"
  
# #######################################
# More Resources:
# apiVersion: v1
# kind: ResourceQuota
# metadata:
#  name: quota2
# spec:
#  hard:
#    cpu: "20"
#    memory: 1Gi
#    pods: "10"
#    replicationcontrollers: "20"
#    resourcequotas: "10"
#    services: "5"
#########################################
