# kubeconfig file for Development namespace
apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: XXXXXXXXXXX
      server: https://api.cloudvishwakarma.in
      tls-server-name: api.internal.cloudvishwakarma.in
    name: cloudvishwakarma.in
contexts:
  - context:
      cluster: cloudvishwakarma.in
      namespace: development
      user: user1
    name: user1-context
current-context: user1-context
kind: Config
users:
  - name: user1
    user:
      client-certificate: /root/user1.crt
      client-key: /root/user1.key



# kubeconfig file for Production namespace
apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: XXXXXXXXXXX
      server: https://api.cloudvishwakarma.in
      tls-server-name: api.internal.cloudvishwakarma.in
    name: cloudvishwakarma.in
contexts:
  - context:
      cluster: cloudvishwakarma.in
      namespace: development
      user: user2
    name: user2-context
current-context: user2-context
kind: Config
users:
  - name: user2
    user:
      client-certificate: /root/user2.crt
      client-key: /root/user2.key
